import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/ui/app-sidebar"
import { JetBrains_Mono } from 'next/font/google';
const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  display: 'swap', // Recommended for better performance and user experience
  variable: '--font-jetbrains-mono', // Define a CSS variable for Tailwind CSS or global use
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Aryan Gupta</title>
        </head>  
      <body
        className={`${jetbrainsMono.className} ${jetbrainsMono.variable}`}
      >
        <SidebarProvider>
        <AppSidebar />
        <SidebarTrigger />
        {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
